// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHQn5efmpl-j-ymo9YR-LujSshCmw201A',
    appId: '1:344336366758:web:e6814e81b7857e945f4867',
    messagingSenderId: '344336366758',
    projectId: 'przychodnia-6e705',
    authDomain: 'przychodnia-6e705.firebaseapp.com',
    storageBucket: 'przychodnia-6e705.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA23iUYrHnctkc1fbdGbvIRpcLKGdWD98U',
    appId: '1:344336366758:android:6f506648bb1a69055f4867',
    messagingSenderId: '344336366758',
    projectId: 'przychodnia-6e705',
    storageBucket: 'przychodnia-6e705.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPcBwxUlpfYS1tAXYfdrX8TEfgyYYYmso',
    appId: '1:344336366758:ios:c017443efc82492b5f4867',
    messagingSenderId: '344336366758',
    projectId: 'przychodnia-6e705',
    storageBucket: 'przychodnia-6e705.firebasestorage.app',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPcBwxUlpfYS1tAXYfdrX8TEfgyYYYmso',
    appId: '1:344336366758:ios:c017443efc82492b5f4867',
    messagingSenderId: '344336366758',
    projectId: 'przychodnia-6e705',
    storageBucket: 'przychodnia-6e705.firebasestorage.app',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHQn5efmpl-j-ymo9YR-LujSshCmw201A',
    appId: '1:344336366758:web:d07810421ae751b35f4867',
    messagingSenderId: '344336366758',
    projectId: 'przychodnia-6e705',
    authDomain: 'przychodnia-6e705.firebaseapp.com',
    storageBucket: 'przychodnia-6e705.firebasestorage.app',
  );
}
